### ISSUE TITLE
Load error

### ISSUE THREAD

**Issue by forditt** [theomenden/TheOmenDen.Vanadium#24]
**Describe the bug**
Load error

**To Reproduce**
Run the client with these mods:
- fabric-api-0.87.0+1.20.1
- modmenu-7.2.1
- sodium-fabric-mc1.20.1-0.5.2
- vanadium-0.1.0-dev

**Expected behavior**
Successful launch to the client :D

**Screenshots**
![image](https://github.com/theomenden/TheOmenDen.Vanadium/assets/105544922/06c40223-7948-4c67-b27d-67d382146251)

**Desktop (please complete the following information):**
 - Windows 11
 - 1.20.1
 - vanadium-0.1.0-dev
 - Fabric Loader Ver. 0.14.22

**Comment by AlucardMG36** [comment]
Reviewing.

**Comment by AlucardMG36** [comment]
This should be fixed in the most recent release.
Also probably because I didn't load up the right file.
