### ISSUE TITLE
Black color of grass and leaves.

### ISSUE THREAD

**Issue by FitchKrause** [theomenden/TheOmenDen.Vanadium#26]
Grass and foliage have a black color instead of the correct color. Curiously, this problem is observed in the foliage of almost all tree species. The exceptions are spruce and birch.

![javaw_NtwprQRnAY](https://github.com/theomenden/TheOmenDen.Vanadium/assets/52543383/dadcf085-851b-41e9-a3e5-9c1b628debac)
![javaw_rYsmt38n3D](https://github.com/theomenden/TheOmenDen.Vanadium/assets/52543383/929499d8-1a1f-4618-adfb-7c56702dfe0a)
![javaw_VF7yawWkxf](https://github.com/theomenden/TheOmenDen.Vanadium/assets/52543383/8c516872-5fee-4041-8e60-9a0d409fff11)

**Comment by AlucardMG36** [comment]
Do you have Indium installed?

**Comment by FitchKrause** [comment]
Currently indium 1.0.23 is installed.

**Comment by AlucardMG36** [comment]
Alright, looks like I'll have to bump up the requirements in the fabric.mod.json
Try updating sodium to 0.5.2 and Indium to the 1.0.25

**Comment by FitchKrause** [comment]
Tested it on a clean build (with sodium 0.5.0 and indium 1.0.23), works fine, the only thing is, as I said, the points for color matching are not correct.

**Comment by craftish37** [comment]
I encounter the same issue with the recent build ([pre-alpha-2](https://github.com/theomenden/TheOmenDen.Vanadium/releases/tag/pre-alpha-2)) and have both the latest of sodium and indium (check [Common-Sense](https://modrinth.com/modpack/common-sense) for the full modlist)

Still haven't fixed it on my side
