### ISSUE TITLE
I encounter the same issue with the recent build ([pre-alpha-2](https://github.com/theomenden/TheOmenDen.Vanadium/releases/tag/pre-alpha-2)) and have both the latest of sodium and indium (check [Common-Sense](https://modrinth.com/modpack/common-sense) for the full modlist)

### ISSUE THREAD

**Issue by AlucardMG36** [theomenden/TheOmenDen.Vanadium#27]
I encounter the same issue with the recent build ([pre-alpha-2](https://github.com/theomenden/TheOmenDen.Vanadium/releases/tag/pre-alpha-2)) and have both the latest of sodium and indium (check [Common-Sense](https://modrinth.com/modpack/common-sense) for the full modlist)

Still haven't fixed it on my side

_Originally posted by @craftish37 in https://github.com/theomenden/TheOmenDen.Vanadium/issues/26#issuecomment-1701320437_
         
         
         Created a new issue for tracking reasons

**Comment by AlucardMG36** [comment]
I don't really know what to do since the referenced modpack is Quilt. 

I understand Quilt _should_ support most fabric mods, however this was not tested on the Quilt loader. 

I can try to make a build specifically for quilt though.

**Comment by FitchKrause** [comment]
I just checked. And the mod works fine with Quilt. I've attached a screenshot of the game. So there is a conflict with one of the mods.
![javaw_aBekGmIvNn](https://github.com/theomenden/TheOmenDen.Vanadium/assets/52543383/de5ea889-ce1c-4d81-8a10-8dabe2fa7a21)

**Comment by craftish37** [comment]
Could you indicate me your modlist on fabric ? We may shorten the list by interposing ours 👀

**Comment by Kirisoup** [comment]
It is not exactly identicle to #26 though, as only grass block would become black, leaves and moss edited by BiomeMoss mod are all behaving normally. 

But this might or might not be the exact issue that @AlucardMG36 encountered since he didn't provided a log or modlist ; ;

**Comment by AlucardMG36** [comment]
> It is not exactly identical to #26 though, as only grass block would become black, leaves and moss edited by BiomeMoss mod (and other colormapped block which aren't effected by LambdaBetterGrass) are all behaving normally.
> 
> But this might or might not be the exact issue that @AlucardMG36 encountered since he didn't provided a log or modlist ; ;

Oh - I don't have this issue. I just created this as a separate one for better tracking. 

This was originally found by @craftish37

**Comment by craftish37** [comment]
Makes sense, I'll test it right away !

**Comment by craftish37** [comment]
Tested with latest modrinth release, seems to work perfectly 👌
