### ISSUE TITLE
CurseForge

### ISSUE THREAD

**Issue by Madis0** [theomenden/TheOmenDen.Vanadium#29]
As I see the mod is already on Modrinth, I suggest uploading it to CurseForge as well to improve awareness and ability to add to modpacks. During the upload, please ensure this toggle is enabled: 
![image](https://github.com/theomenden/TheOmenDen.Vanadium/assets/8611110/480c6afd-f0f2-43ad-85cf-825d51c53346)

**Comment by AlucardMG36** [comment]
At this time, I have no interest in working with curseforge.

I give no permissions to upload the mod to curseforge either, though I doubt they'll do much to stop that.

I might change my mind in the future.

**Comment by Madis0** [comment]
> I give no permissions to upload the mod to curseforge either, though I doubt they'll do much to stop that.

I assume you meant "upload" as in "fork and upload under someone's name with minimal changes"? What about [allowing modpacks to host _your JARs_ in CurseForge](https://support.curseforge.com/en/support/solutions/articles/9000197913-non-curseforge-mods)?

**Comment by AlucardMG36** [comment]
I will look into this, but no guarantees - especially as this is an alpha build right now. 

For betas and releases? Absolutely I'll be open to allowing modpacks to open my JARs.

**Comment by AlucardMG36** [comment]
> > I give no permissions to upload the mod to curseforge either, though I doubt they'll do much to stop that.
> 
> I assume you meant "upload" as in "fork and upload under someone's name with minimal changes". What about [allowing modpacks to host _your JARs_ in CurseForge](https://support.curseforge.com/en/support/solutions/articles/9000197913-non-curseforge-mods)?
> 
> For example, Sodium, Iris and Mod Menu are all fine with that because the integrity is preserved, even though these mods do not upload to CurseForge themselves anymore.

I've uploaded Vanadium and Bismuth to curseforge - pending approval.
