### ISSUE TITLE
Mod Menu requirement?

### ISSUE THREAD

**Issue by Madis0** [theomenden/TheOmenDen.Vanadium#30]
The other dependencies of the mod make sense as the mod could break without config lib, could depend on Sodium's internal features and so on. But why require Mod Menu and especially a specific version of it?

**Comment by AlucardMG36** [comment]
It should be requiring a version greater than or equal to, not necessarily specific. That just happens to be the latest version out right now. 
This will also not be removed.

**Comment by Madis0** [comment]
Well, why is there though? There is already [at least one competitor to Mod Menu](https://www.curseforge.com/minecraft/mc-mods/catalogue-fabric) and some users may just use config files anyway.

**Comment by AlucardMG36** [comment]
I see. Removed.
