### ISSUE TITLE
[Question] Can this mod be considered a partial OptiFine alternative?

### ISSUE THREAD

**Issue by Kasualix** [theomenden/TheOmenDen.Vanadium#34]
![IMG_20230910_001939](https://github.com/theomenden/TheOmenDen.Vanadium/assets/110756250/b9425fa8-2fed-42c3-9ecd-71bd2ae1fd92)
Saw this, but still not sure.

**Comment by AlucardMG36** [comment]
Technically yes - but it's still in alpha stage and a bit unstable.

**Comment by Kasualix** [comment]
Ok, thank you!
