### ISSUE TITLE
strange colors of grass

### ISSUE THREAD

**Issue by forditt** [theomenden/TheOmenDen.Vanadium#41]
The mod without any additions changes the color of the vanilla grass, please add a setting that will return the grass to the standard version.
![image](https://github.com/theomenden/TheOmenDen.Vanadium/assets/105544922/35378f5f-63aa-415f-92c8-5d8f798f943c)

**Comment by AlucardMG36** [comment]
This is due to the way we interface with Sodium 0.5.x - A fix for this discoloration is on the way.

**Comment by forditt** [comment]
I understand, thank you
