### ISSUE TITLE
Doesn't work with the xp bar number in the color.properties folder.

### ISSUE THREAD

**Issue by QfBone** [theomenden/TheOmenDen.Vanadium#55]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Minecraft Version [e.g. 1.20, 1.20.1]
 - Mod Version [e.g. 1.0]

**Additional context**

**Comment by AlucardMG36** [comment]
No context, please provide more information such as mod lists, logs, etc. Closing this, but noting the issue to resolve further.
